import './globals.css';
import './style.css';
import { Open_Sans } from 'next/font/google';
import Footer from '@/components/common/Footer';
import MobileMenu from '@/components/navbar/MobileNavbar';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <MobileMenu />
        <main className="main_content "> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
